name: UltimatePlugin
version: 1.0.0
main: ca.sajid.ultimateplugin.UltimatePlugin
api-version: 1.16
commands:
  author:
    description: Authors
    usage: /<command>
    permission: up.author
  sudo:
    description: Executes a command or a chat message as another player with full permissions
    usage: /<command> [player] [c:message | command]
    permission: up.sudo
