name: UltimatePlugin
version: 1.0.0
authors: [ ShrimpyStuff, ElCholoGamer ]
main: ca.sajid.ultimateplugin.UltimatePlugin
api-version: 1.16

commands:
  sudo:
    description: Executes a command or a chat message as another player with full permissions
    usage: /<command> [player] [c:message | command]
    permission: up.sudo
  inventory:
    description: See a player's inventory
    usage: /<command> [player]
    aliases: [ inv ]
    permission: up.inventory
  lightning:
    description: Strikes lightning at the center of all loaded chunks
    usage: /<command>
    permission: up.lightning
  horses:
    permission: up.horses
    usage: /<command>
  sans:
    permission: up.sans
    usage: /<command>

permissions:
  up.*:
    description: Permission to use all UltimatePlugin commands
    default: op
    children:
      up.inventory:
        description: Permission to use the inventory command
      up.sudo:
        description: Permission to use the sudo command
      up.lightning:
        description: Permission to use the lightning command
      up.horses:
        default: true
        description: Permission to use the horses command
      up.sans:
        description: Permission to use the sans command