name: UltimatePlugin
version: 1.0.0
main: ca.sajid.ultimateplugin.UltimatePlugin
api-version: 1.16
commands:
  Bricks:
    description: Gives player 20 bricks
    usage: /<command>
    permission: up.bricks
  sudo:
    description: Executes a command or a chat message as another player with full permissions
    usage: /<command> [player] [c:message | command]
    permission: up.sudo
