name: UltimatePlugin
version: 1.0.0
main: ca.sajid.ultimateplugin.UltimatePlugin
api-version: 1.16
commands:
  author:
    description: Authors
    usage: /<command>
  sudo:
    description: Executes a command or a chat message as another player with full permissions
    usage: /<command> [player] [c:message | command]
  inventory:
    description: See a player's inventory
    usage: /<command> [player]
    aliases: [ inv ]

permissions:
  up.author:
    default: true
  up.inventory:
    default: op
  up.sudo:
    default: op