name: UltimatePlugin
version: 1.0.0
main: ca.sajid.ultimateplugin.UltimatePlugin
api-version: 1.16
commands:
  author:
    description: Authors
    usage: /<command>
  sudo:
    description: Executes a command or a chat message as another player with full permissions
    usage: /<command> [player] [c:message | command]
    permission: up.sudo
  inventory:
    description: See a player's inventory
    usage: /<command> [player]
    aliases: [inv]
    permission: up.inventory
permissions:
  up.author:
    default: true
  up.inventory
  up.sudo